[project]
name = "Nasa.py"
description = "A python API wrapper for the NASA API"
readme = "README.md"
authors = [
    { name = "Snipy7374" }
]
requires-python = ">=3.10"
keywords = ["Nasa", "Nasa.py", "Nasa API"]
license = { text = "MIT" }


[tool.pyright]
typeCheckingMode = "strict"

reportUnusedImport = false
reportUnknownParameterType = false
reportUnknownArgumentType = false
reportUnknownMemberType = false
reportMissingParameterType = false
reportUnnecessaryIsInstance = false